### ISSUE TITLE
Migrate to tenv from tfenv

### ISSUE THREAD

**Issue by kvendingoldo** [kaiohenricunha/devenv#1]
Hi! I saw that you're using tfenv in this repository. It's a really good tool, but it does not support OpenTofu and Terragrunt. My team designed a successor of tenv that support Terraform, Terragrunt and OpenTofu. It will be a good idea to migrate into it in due to the growing popularity of OpenTofu.
url: https://github.com/tofuutils/tenv

**Comment by kaiohenricunha** [comment]
Sounds good. I'll take a look as soon as I have more time. One of the docker environments is not even functional yet.

Thanks!

**Comment by kaiohenricunha** [comment]
> Hi! I saw that you're using tfenv in this repository. It's a really good tool, but it does not support OpenTofu and Terragrunt. My team designed a successor of tenv that support Terraform, Terragrunt and OpenTofu. It will be a good idea to migrate into it in due to the growing popularity of OpenTofu. url: https://github.com/tofuutils/tenv

I've just updated the setup with `tenv`. Thanks.

**Comment by kvendingoldo** [comment]
Wow! Great!
